import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "./_components/Aside";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./_components/AuthProvider";
import { getUserSession } from "@/utils/getSessionUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <main>

            {children}
            <Toaster />
          </main>
        </body>
      </html>
    </AuthProvider>
  );
}
