import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "./_components/Aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="grid grid-cols-[auto_1fr] min-h-screen bg-[#f8f4f0]">
      <Aside/>
        {children}
        </main>
        </body>
    </html>
  );
}
