import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "./_components/Aside";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./_components/AuthProvider";
import { getUserSession } from "@/utils/getSessionUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getUserSession();
  
  return (
    <AuthProvider>
      <html lang="en">
      <body className={inter.className}>
      <main className="grid grid-cols-[auto_1fr] min-h-screen bg-[#f8f4f0]">
      {
        session && (<Aside/>)
      }
        {children}
        <Toaster />
        </main>
        </body>
    </html>
    </AuthProvider>
  );
}
